#!/bin/bash

# export FC_DOCKER_VERSION=1.10.8
# export fc_component_version=fc3@dev.0.1

echo "test custom-container runtime ..."
s3 build
s3 local invoke -e '{"hello":"fc custom-container"}'
s3 deploy -y 
s3 invoke -e '{"hello":"fc custom-container"}'
