#!/bin/bash

set -e

echo "test custom-container runtime ..."
export fc_component_function_name=custom_container-$(uname)-$(uname -m)
s build --dockerfile ./code/Dockerfile
s deploy -y 
s invoke -e '{"hello":"fc custom-container"}'
s info
s remove -y
