#!/bin/bash

set -e
set -v 

export layer_name=pyyaml-layer-$(uname)-$(uname -m)-$RANDSTR

echo "test layer"

s3 layer list 

s3 layer list --prefix python

s3 layer info --layer-name Python39-Aliyun-SDK --version-id 2

s3 layer download --layer-name Python39-Aliyun-SDK --version-id 2

s3 layer publish --layer-name $layer_name --code ./pyyaml-layer.zip --compatible-runtime "python3.9,python3.10,custom,custom.debian10"

s3 layer list --prefix $layer_name

s3 layer list --prefix $layer_name --table

s3 layer versions --layer-name $layer_name

s3 layer remove -y --layer-name $layer_name