#!/bin/bash

set -e

# export FC_DOCKER_VERSION=1.10.8
# export fc_component_version=fc3@dev.0.1

echo "test apt-get ..."
rm -rf ./code/apt-archives
rm -rf ./code/node_modules
export fc_component_function_name=nodejs14-$(uname)-$(uname -m)
s3 build
s3 local invoke -e '{"hello":"apt-get"}'
s3 deploy -y 
s3 invoke -e '{"hello":"apt-get"}'
s3 info
s3 remove -y
