#!/bin/bash

set -e

# export FC_DOCKER_VERSION=1.10.8
# export fc_component_version=fc3@dev.0.1

echo "test php runtime ..."
rm -rf ./code/vendor
export fc_component_function_name=php72-$(uname)-$(uname -m)
s3 build
s3 local invoke -e '{"hello":"fc php"}'
s3 deploy -y 
s3 info
s3 invoke -e '{"hello":"fc php"}'
s3 remove -y
