#!/bin/bash

# export FC_DOCKER_VERSION=1.10.8
# export fc_component_version=fc3@dev.0.1

echo "test php runtime ..."
rm -rf ./code/vendor
s3 build
s3 local invoke -e '{"hello":"fc php"}'
s3 deploy -y 
s3 invoke -e '{"hello":"fc php"}'
s3 remove -y
