#!/bin/bash

set -e

# java8
export fc_component_runtime=java8
echo "test java8 runtime ..."
rm -rf ./target
export fc_component_function_name=java8-$(uname)-$(uname -m)
s3 deploy -y 
s3 local invoke -e '{"hello":"fc java8"}'
s3 invoke -e '{"hello":"fc java8"}'
s3 info
s3 remove -y

# java11
export fc_component_runtime=java11
echo "test java11 runtime ..."
rm -rf ./target
export fc_component_function_name=java11-$(uname)-$(uname -m)
s3 deploy -y 
s3 local invoke -e '{"hello":"fc java11"}'
s3 invoke -e '{"hello":"fc java11"}'
s3 remove -y
