#!/bin/bash

set -e

echo "test custom go runtime ..."
rm -rf ./code/go.sum
export fc_component_function_name=go1-$(uname)-$(uname -m)
s deploy -y
s invoke -e '{"hello":"fc go1"}'
s local invoke -e '{"hello":"fc go1"}'
s info
s remove -y
rm -rf ./code/target