#!/bin/bash

set -e

echo "test dotnetcore3.1 runtime ..."
rm -rf ./HelloFcApp/target
export fc_component_function_name=dotnetcore31-$(uname)-$(uname -m)
# s build
# s local invoke -e '{"hello":"fc dotnetcore3.1"}'
s deploy -y 
s info
s invoke -e '{"hello":"fc dotnetcore3.1"}'
s remove -y
